// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfLW0qYLJt5VuuflCGGK2w41gX5FubbhM',
    appId: '1:507100052744:web:2e3edacf709690045380bd',
    messagingSenderId: '507100052744',
    projectId: 'kakeibo-memo',
    authDomain: 'kakeibo-memo.firebaseapp.com',
    storageBucket: 'kakeibo-memo.appspot.com',
    measurementId: 'G-GPLV92GVJ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeYbSWo5rLTIQ_-ZbTp7PFPvqKNipvGFw',
    appId: '1:507100052744:android:ec1dd2a3d3e2d56f5380bd',
    messagingSenderId: '507100052744',
    projectId: 'kakeibo-memo',
    storageBucket: 'kakeibo-memo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo1tpxu6mLXlbLZLJIf3dshcw2R6QAo5A',
    appId: '1:507100052744:ios:d90212b44bf3e6805380bd',
    messagingSenderId: '507100052744',
    projectId: 'kakeibo-memo',
    storageBucket: 'kakeibo-memo.appspot.com',
    iosBundleId: 'com.example.furukawapuru.kakeibo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBo1tpxu6mLXlbLZLJIf3dshcw2R6QAo5A',
    appId: '1:507100052744:ios:93894d225acefb925380bd',
    messagingSenderId: '507100052744',
    projectId: 'kakeibo-memo',
    storageBucket: 'kakeibo-memo.appspot.com',
    iosBundleId: 'com.example.kakeibo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfLW0qYLJt5VuuflCGGK2w41gX5FubbhM',
    appId: '1:507100052744:web:2c2bd3562cacecee5380bd',
    messagingSenderId: '507100052744',
    projectId: 'kakeibo-memo',
    authDomain: 'kakeibo-memo.firebaseapp.com',
    storageBucket: 'kakeibo-memo.appspot.com',
    measurementId: 'G-L9882VD1LF',
  );
}
